### ISSUE TITLE
To-do: Synoptic

### ISSUE THREAD

**Issue by carlalopezll** [carlalopezll/Delmarva-GHG#1]
- [x] Fix CH4 calculations- WAY TOO HIGH
- [x] Add missing temperatures
- [x] Finalize systematic correction for air
- [x] Add uatm to uM conversions
- [x] Merging full GHG dataset across synoptic dates
- [x] Fix dates to MM-DD-YYYY
- [x] Remove outliers (post-preliminary analysis)
- [x] Write NAs in missing fields
